### ISSUE TITLE
- Grenades not working

### ISSUE THREAD

**Issue by STX-Garand** [iamthesux/KingsHorses#10]
- Grenades not working

**Comment by LewisSO** [comment]
Believe this is a feature thats not being used within AGM. In order to use grenades or throw grenades you must first ready it, Check AGM bindings for lethal and non lethal selection of grenades. CTRL G is default grenade selection and must be used to select the grenade desired before it can be thrown. If this is not the issue then feel free to re open.

**Comment by doddsde** [comment]
Looks to be you have to choose grenade before throwing.  Tested.  Issue can be closed.
