### ISSUE TITLE
When using tripod based weapons and the weapon is disassembled when someone is on it, that person dissapears.

### ISSUE THREAD

**Issue by doddsde** [iamthesux/KingsHorses#43]

**Comment by LewisSO** [comment]
Not 100% sure on how we can fix this, it is most likely the engine doing this and would be very time consuming to remove. It is not fully game breaking in my eyes because the amount of times people are going to disassemble this while people are on it are most likely very minimal and the fact that you are able to bring the person back by assembling it back up makes it a fixable bug in game.

**Comment by doddsde** [comment]
Not game breaking and to time consuming.  Closed.
